name: Run Quality Gate

run-name: Running Quality Gate on ${{ github.ref }}

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Lint
        run: npm run lint